### ISSUE TITLE
How to set the word colors to be based on weight?

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [guo-yong-zhi/WordCloud.jl#15]
Thanks for this package. I am testing it at the moment and was not able to find out how to set word colors such that the color depends on the weight (based on occurrence). This could perhaps create a nice gradient of color rather than the random look I seem to get. 

I've reproduced the code I'm using at the moment here: 

```julia
using WordCloud

stopwords = WordCloud.stopwords_en
textfile = "/home/kevin/Desktop/temp.txt"
mydata = lowercase(read(textfile, String)) 

wc = wordcloud(
        processtext(mydata, stopwords=WordCloud.stopwords_en), 
        angles=(0, 90), 
        density=0.7,     
        mask=ellipse,   
        outline = 0,
        colors = :seaborn_dark,#colors = :Set1_5,
        fonts = "Tahoma",
        backgroundcolor="white",
        state=initwords!)
    placewords!(wc, style=:gathering, level=6)#, centeredword="modelling")
    pin(wc, "modelling") do # keep "modelling" in the center        
        generate!(wc, reposition=0.5) # don't teleport largest 30% words
        #generate!(wc)
    end

paint(wc, "/home/kevin/Desktop/plot.svg",background=true)
```

Currently I get something like: 
![image](https://user-images.githubusercontent.com/8392709/175319480-a7241b5f-c60b-4b5b-8409-ed5ccf5a4d4f.png)

But I would prefer if it would look more like this: 
![image](https://user-images.githubusercontent.com/8392709/175319302-59bfa915-e2a0-457f-aacc-898571a8f4eb.png)

**Comment by guo-yong-zhi** [comment]
I'm sure we can make something similar, or even better, for example, [this picture](https://github.com/guo-yong-zhi/WordCloud-Gallery/blob/main/fromweb.svg). To do that, you need a weight-ordered word list and a corresponding color list. If you pass a `Vector` to the `colors` argument, the item will be used one by one in cycle. 
So if you want the style of your second picture, you may need to set `colors =  [repeat(["gray"], 100); repeat(["red"], 100); repeat(["purple"], 100); repeat(["orange"], 100); repeat(["green"], 100)]`(suppose the length of word list is 500). 
Of course, you can set a more fine grain gradient colors (like my picture). You can refer to [my approach](https://github.com/guo-yong-zhi/WordCloud.jl/blob/0a0311bfa9f042a253ba7cf5ea61ceb4e8ac6c5a/src/artist.jl#L76-L81).

**Comment by Kevin-Mattheus-Moerman** [comment]
@guo-yong-zhi :wave: any chance you can help with this? Thanks!

**Comment by Kevin-Mattheus-Moerman** [comment]
That did the trick thanks! 

![plot10](https://user-images.githubusercontent.com/8392709/176426658-c67f30a1-5896-4da9-b07a-b7a8339ca66d.svg)

**Comment by guo-yong-zhi** [comment]
I added a new function [`WordCloud.gradient`](https://github.com/guo-yong-zhi/WordCloud.jl/blob/ddd751d11778dcd473b0b75e9da161e97a042e01/src/artist.jl#L59) to make it easy to generate gradients. Maybe I'll add an example sometime.
