### ISSUE TITLE
Wordcloud for custom png and texts

### ISSUE THREAD

**Issue by glanzkaiser** [guo-yong-zhi/WordCloud.jl#16]
Hi @guo-yong-zhi ,

I am trying to create my own png and words, but it still calling the texts from alice.txt

I have created the .jl in examples directory as well. Is my code is right?

![Capture d’écran_2022-08-01_13-43-28](https://user-images.githubusercontent.com/72222484/182088302-98293663-078f-456d-979d-65e39979997d.png)

**Comment by glanzkaiser** [comment]
Solved it, turns out needs permission of super user to create file in package.

![freya](https://user-images.githubusercontent.com/72222484/182089760-6f67fcb6-dcea-484d-bd67-9c6ee61c4b91.png)

**Comment by guo-yong-zhi** [comment]
You don't need to put anything into package's examples directory. You should put your txt and png on your current work directory, then replace the `pkgdir(WordCloud)*"/res/alice.txt"` with `"./freya.txt"` and replace the `pkgdir(WordCloud)*"/res/alice_mask.png"` with `"./Freya.png"`. It should work.

**Comment by guo-yong-zhi** [comment]
And the last line `runexample(:freya)` should be removed.

**Comment by glanzkaiser** [comment]
I see, we can look for file in current directory, thanks.

**Comment by guo-yong-zhi** [comment]
exactly.
