### ISSUE TITLE
Display seems to be full of bars of numbers

### ISSUE THREAD

**Issue by Rratic** [guo-yong-zhi/WordCloud.jl#18]
I tried the example:
```jl
using WordCloud
using Random
words = [randstring(rand(1:8)) for i in 1:300]
weights = randexp(length(words))
wc = wordcloud(words, weights)
generate!(wc)
paint(wc, "D:/random.svg")
```

and this is what it looks like:
![random](https://user-images.githubusercontent.com/73381027/211608084-9098fb9d-d97f-4df8-8231-fdc75d801d35.svg)

environment:
```jl
julia> versioninfo()
Julia Version 1.8.4
Commit 00177ebc4f (2022-12-23 21:32 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 8 × Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-13.0.1 (ORCJIT, skylake)
  Threads: 1 on 8 virtual cores

(@v1.8) pkg> st WordCloud
Status `C:\Users\anonymous\.julia\environments\v1.8\Project.toml`
  [6385f0a0] WordCloud v0.10.7
```

**Comment by guo-yong-zhi** [comment]
Please see https://github.com/guo-yong-zhi/WordCloud-Gallery/issues/1
You can temporarily solve the problem with `] add Pango_jll` and `] pin Pango_jll@1.42.4`.

**Comment by eohne** [comment]
Hi this problem still exists. I also get the same image as above - just numbers in boxes. Unfortunately, once I pin Pango_jll@1.42.4 WordCloud fails precompilation.
Any other solutions?

Edit: Since pinning and the package are not recompiling, I unpinned and updated WordCloud precompilation is failing regardless of what I do...

**Comment by guo-yong-zhi** [comment]
Thank you for your feedback @eohne . I've found that the compatibility of pango in the new version of Windows 11 and Julia 1.10 has become even worse. ~As a result, I have disabled the random font feature in WordCloud.jl on Windows, which sometimes leads to errors. Operating systems other than Windows, such as Linux, are unaffected and will remain unchanged. Please try the latest version of WordCloud.jl (0.13.3 or above).~ 
I have developed a new font random selecting mechanism. Please try the WordCloud.jl 0.13.6 or above. The precompilation failure issue has been fixed, but the pango issue remains. So the pinning is still needed.

**Comment by guo-yong-zhi** [comment]
pango issue fixed. see https://github.com/JuliaGraphics/Cairo.jl/issues/349#issuecomment-2308411753

**Comment by eohne** [comment]
Thanks a lot for the update! 

Best
Elias
