### ISSUE TITLE
s-ending words are not portable to other language

### ISSUE THREAD

**Issue by samuelortion** [guo-yong-zhi/WordCloud.jl#25]
The hard coded s_ending_words is well suited to English, however, when I run WordCloud.jl on a French text, I encounter several s_ending words which get stripped by lemmatize (such as dans->dan, nou->nous, etc.), which makes the wordcloud less meaningful.

A workaround would be to be able to specify other s_ending_words as an argument to `lemmatize` function (that may be used in the `process` option of processwords.

What could I do otherwise ?

**Comment by guo-yong-zhi** [comment]
The `s_ending_words` list and the `lemmatize!` function are designed for English, and French follows different lexical rules. So, simply adding `s_ending_words` as an argument may not be sufficient, I guess. 
Perhaps I can find a better way to prevent the negative impact of the English `lemmatize!` function on other languages (Do you have any suggestions?), but for now, you have two options. First, you can remove the `lemmatize!` function from the option `process` . This may be enough in certain cases. Second, you can implement a `lemmatize_fr!` function specifically for French and include it in the option `process`. This would allow you to further enhance the quality of the results. 
Additionally, to make the word cloud more meaningful, you could use a French stopword list. 
Here's an example:

```julia
using WordCloud

stopwords_fr = [
    "à", "aussi", "autre", "avant", "avec", "avoir", "bon", "car", 
    "ce", "cela", "ces", "cet", "cette", "ceux", "chaque", "comme", 
    "dans", "de", "des", "du", "elle", "en", "et", "eux", "être", 
    "faire", "il", "je", "la", "le", "les", "leur", "lui", "ma", 
    "mais", "mes", "moi", "mon", "ne", "notre", "nous", "ou", 
    "par", "pas", "pour", "que", "qui", "se", "son", "sur", "ta",
    "te", "toi", "ton", "tu", "un", "une", "vos"
]

wordcloud(processtext(
	"Nous allons danser dans la salle de bal.", 
	stopwords = stopwords_fr,
	process = rescaleweights(identity, 0) ∘ casemerge!, 
	# The default is `process = rescaleweights(identity, 0) ∘ casemerge! ∘ lemmatize!`
)) |> generate!
```
If you need more complex text processing, I recommend using other specialized tools and then passing the processed data to the `wordcloud` function, similar to how it's done in [this example](https://github.com/guo-yong-zhi/WordCloud-Gallery#languages).
